# Generated by Django 5.0.4 on 2024-04-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Anonymous', 'Anonymous'), ('Student', 'Student'), ('Teacher', 'Teacher')], default='Anonymous', max_length=10, null=True),
        ),
    ]
