# Generated by Django 5.0.4 on 2024-04-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_access',
            field=models.BooleanField(default=False),
        ),
    ]
