# Generated by Django 5.0.6 on 2024-05-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="login_code",
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
