# Generated by Django 5.0.4 on 2024-05-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_login_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Anonymous', 'Anonymous'), ('Student', 'Student'), ('Teacher', 'Teacher'), ('Mentor', 'Mentor')], default='Anonymous', max_length=10, null=True),
        ),
    ]
