# Generated by Django 5.0.4 on 2024-07-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_last_opened_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_opened_course',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_opened_course_date',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_opened_content_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
