# Generated by Django 5.0.4 on 2024-08-22 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_customuser_last_opened_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admission_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна поступление'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончание договора'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Класс обучения'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата регистрации'),
        ),
    ]
