# Generated by Django 5.0.4 on 2024-06-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_advertisement_news_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='advertisement',
        ),
        migrations.RemoveField(
            model_name='news',
            name='quote',
        ),
    ]
