# Generated by Django 5.0.4 on 2024-05-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_delete_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttime',
            name='date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
