# Generated by Django 5.0.4 on 2024-08-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_shifttime_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifttime',
            name='date',
        ),
        migrations.AddField(
            model_name='shifttime',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
            preserve_default=False,
        ),
    ]
