# Generated by Django 5.0.4 on 2024-04-11 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=24)),
                ('lesson_type', models.CharField(max_length=12)),
                ('video_link', models.CharField(max_length=200)),
                ('lesson_test', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LessonLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literature_name', models.CharField(max_length=20)),
                ('literature_type', models.CharField(choices=[('Book', 'Book'), ('Video', 'Video'), ('Text', 'Text'), ('Audio', 'Audio')], max_length=6)),
                ('file', models.FileField(upload_to='lesson_literature')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
            ],
        ),
    ]
