# Generated by Django 5.0.4 on 2024-04-16 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_testsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestSubmission',
        ),
    ]
