# Generated by Django 5.0.4 on 2024-04-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_question_audio_question_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_success_video',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/'),
        ),
    ]
