# Generated by Django 5.0.6 on 2024-05-13 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_course_course_success_video"),
        ("courses", "0010_rating"),
    ]

    operations = []
