# Generated by Django 5.0.4 on 2024-04-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_course_success_video'),
        ('courses', '0010_rating'),
    ]

    operations = [
    ]
