# Generated by Django 5.0.4 on 2024-04-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_merge_0010_course_course_success_video_0010_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsubmission',
            name='selected_answers',
            field=models.ManyToManyField(related_name='user_checked_answers', to='courses.answer'),
        ),
    ]
