# Generated by Django 5.0.4 on 2024-05-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
