# Generated by Django 5.0.4 on 2024-05-30 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_message_options_message_message_type'),
        ('subjects', '0012_grouptemplate_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='subjects.task'),
        ),
    ]
