# Generated by Django 5.0.4 on 2024-05-15 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message_file_alter_message_message'),
        ('subjects', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_crm2',
            name='chat_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='chats.chatroom'),
            preserve_default=False,
        ),
    ]
