# Generated by Django 5.0.4 on 2024-05-17 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('subjects', '0004_subject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_crm2',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule'),
        ),
    ]
