# Generated by Django 5.0.4 on 2024-05-17 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_shift_shifttime'),
        ('subjects', '0005_lesson_crm2_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_crm2',
            name='shift',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.shift'),
            preserve_default=False,
        ),
    ]
