# Generated by Django 5.0.4 on 2024-05-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_lesson_crm2_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_crm2',
            name='schedule',
        ),
    ]
