# Generated by Django 5.0.4 on 2024-05-17 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_shift_shifttime'),
        ('subjects', '0007_remove_lesson_crm2_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_crm2',
            name='shift',
        ),
        migrations.AddField(
            model_name='lesson_crm2',
            name='time_slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.shifttime'),
            preserve_default=False,
        ),
    ]
