# Generated by Django 5.0.4 on 2024-05-20 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message_file_alter_message_message'),
        ('subjects', '0009_volunteerchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerchannel',
            name='chat_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.chatroom'),
        ),
    ]
