# Generated by Django 5.0.4 on 2024-05-23 05:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0011_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
