# Generated by Django 5.0.4 on 2024-06-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0012_grouptemplate_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_crm2',
            name='google_meet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
