# Generated by Django 5.0.4 on 2024-06-10 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0017_achievement_studentachievement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='students',
            field=models.ManyToManyField(related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='difficulty',
            field=models.PositiveIntegerField(),
        ),
    ]
