# Generated by Django 5.0.4 on 2024-06-25 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0019_volunteerchannel_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_crm2',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'Student'}, related_name='lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson_crm2',
            name='group_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.grouptemplate'),
        ),
    ]
