# Generated by Django 5.0.4 on 2024-06-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0021_alter_grouptemplate_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_crm2',
            name='date',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
